# Generated by Django 3.2 on 2021-06-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Image',
            new_name='image',
        ),
    ]
